import type { NextPage, GetStaticProps } from "next";
// import { PageLayout, PageTitle, Section } from "components";

import { GiFireplace, GiCauldron, GiWarlockEye } from "react-icons/gi";

import PageLayout from "@components/layout/PageLayout";
import PageTitle from "@components/shared/PageTitle";
import Section from "@components/shared/Section";

// import { PageTitle } from "@components/shared";
// import { PageLayout } from "@components/";

// import PageTitle from "@components/shared/PageTitle";
// import PageLayout from "@components/layout/PageLayout";

import { TimeLineData, TestimonialData } from "../utils/constants";
import { ITimeline, ITestimonial } from "../interfaces";

interface IProps {
  timeline: ITimeline[];
  testimonial: ITestimonial[];
}

export const getStaticProps: GetStaticProps = async () => {
  const timeline = await TimeLineData;
  const testimonial = await TestimonialData;

  return { props: { timeline, testimonial } };
};

const title = "Hi, I'm  James 'Dante'";
const subtitle =
  "I am a Draziw, Curator and Professor. I believe that knowledge should be shared, and I try to do my part in that regard each day. I am on a journey to become a reknown Potions Master.";

const Home: NextPage<IProps> = ({ timeline, testimonial }) => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <PageLayout pageMeta={{ title: "Potions Room" }}>
        <PageTitle title={title} subtitle={subtitle} icons />

        {/* <img src="/assets/hallows.svg" /> */}
        <div className="bg-white p-5">
          <img src="/result.svg" width="30px" height="30px" />
        </div>

        <Section linebreak>
          <h2 className="mb-5 font-headingAlt text-2xl font-semibold text-gray-100 md:text-3xl">
            Take a trip through my pensieve
          </h2>
          <div className=" grid grid-cols-1 gap-6 md:grid-cols-2">
            {timeline.reverse().map((event) => (
              <div className="flex flex-col justify-between rounded-md bg-black p-4 text-gray-300 shadow shadow-gray-500">
                <h3 className="text-base">{event.text}</h3>
                <p>{event.year}</p>
              </div>
            ))}
          </div>
        </Section>
        <Section>
          <h2 className="mb-5 font-headingAlt text-2xl font-semibold text-gray-100 md:text-3xl">
            People I've Worked With
          </h2>
          <div className=" grid grid-cols-1 gap-6 md:grid-cols-2">
            {testimonial.map((client) => (
              <div className="flex flex-col justify-between rounded-md bg-black p-4 text-gray-300 shadow-xl">
                <h3 className="text-base">{client.name}</h3>
                <p>{client.message}</p>
              </div>
            ))}
          </div>
        </Section>
        <Section>
          <h2 className="mb-4 font-headingAlt text-2xl font-semibold text-gray-100 md:text-3xl">
            Marauder's Map
          </h2>
          <p className="flex items-center text-lg md:text-xl">
            <GiWarlockEye className="mr-1" /> - Take you away from this manor
          </p>
          <p className="flex items-center text-lg md:text-xl">
            <GiCauldron className="mr-1" /> - Take you to details about a potion
          </p>
          <p className=" flex items-center text-lg md:text-xl">
            <GiFireplace className="mr-1" /> - Take you to another area of this
            manor
          </p>
        </Section>
      </PageLayout>
    </>
  );
};

export default Home;
