import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Meta from "../components/SEO/Meta"
import styles from '../styles/Home.module.css'

export interface IPageMeta  {
  title?: string
  description?: string
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Meta
     pageMeta={{
       title: "Potions Room"
     }}
      />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Potions Room!
        </h1>

     <div className="page"></div>
       
      </main>

    
      
    </div>
  )
}

export default Home
